sudo: required
services:
  - docker
language: go
go:
  - 1.12
env:
  global:
    - CGO_ENABLED=0
install: true
script:
  - go build
  - ls
  - docker image build -t mytest/web:$TRAVIS_BRANCH . 
after_success:
  - if [ -n "$TRAVIS_TAG}" ] ; then
      docker login -u="${DOCKER_USER}" -p="${DOCKER_PASSWORD}";
      docker push mytest/web:$TRAVIS_BRANCH;
    fi
